Add Dashboard UI Tests
PSE-SS2022/Timefy-Android pull request #56
Opened 2022-08-23 18:41 UTC by telip007

Added automated UI tests for the `DashboardView` composable.

2022-08-23 20:34 UTC, Andreas-Noebel requested changes
Great work! There are just two tiny issues, otherwise it looks good to me

2022-08-23 20:34 UTC, Andreas-Noebel commented on app/src/androidTest/java/com/pse2022/timefy/ui/dashboard/DashboardUiTest.kt
> +		"startDate": 0,
```suggestion
		"startDate": 3600,
```
If we want to test the 01.01.1970 01:00 - 02:00, this has to be 3600

2022-08-23 20:34 UTC, Andreas-Noebel commented on app/src/androidTest/java/com/pse2022/timefy/ui/dashboard/DashboardUiTest.kt
> +		"startDate": 0,
```suggestion
		"startDate": 3600,
```
Same applies to this

2022-08-24 12:17 UTC, telip007 commented on app/src/androidTest/java/com/pse2022/timefy/ui/dashboard/DashboardUiTest.kt
> +		"startDate": 0,
Actually for me it is `0` because in our time zone `3600` equals to `Jan 01 1970 02:00:00 GMT+0100 (CET)`

2022-08-24 12:18 UTC, telip007 commented on app/src/androidTest/java/com/pse2022/timefy/ui/dashboard/DashboardUiTest.kt
> +		"startDate": 0,
Dito.

2022-08-24 13:21 UTC, Andreas-Noebel approved these changes

2022-08-24 13:21 UTC, merged